# Site settings
name: "Ian Carrico: Web Developer"
description: "Ian Carrico is a web developer based in Austin, TX with his hands in many open source projects."
baseurl: "https://www.iancarrico.com"
url: "https://www.iancarrico.com"

# Development settings
development: false
debug: false

# Display settings
markdown: kramdown
permalink: pretty
lsi: false

# Pagination
paginate: 10
paginate_path: "page:num"

# Build settings
timezone: America/Chicago
future: false
exclude:
  - CONTRIBUTING.md
  - README.md
  - config.rb
  - package.json
  - gulpfile.js
  - node_modules
  - Gemfile
  - Gemfile.lock
  - css

collections:
  work:
    start_date: nil
    end_date: nil
    postion: nil
    organization: nil
    location: nil
  education:
    grad_date: nil
    degree: nil
    school: nil
    location: nil



# Extra gems to have fancy things.
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Asset Pipeline settings
assets:
  dirname: assets
  sources:
    - js
    - css
    - img
    - bower_components
  js_compressor: 'uglifier'
  css_compressor: 'yui'
  cache: true
